kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: flaskapp-service
  namespace: flask

spec:
  rules:
    - host: {{ .Values.hostName }}
      http:
        paths:
          - path: /crud
            backend:
              serviceName: flaskapi-service
              servicePort: 80